baseURL = 'https://github.com/Luhuizu/My-Little-Blog.git'
languageCode = 'en-us'
title = 'My New Hugo Site'
[module]
 [[module.imports]]
  path = "github.com/panr/hugo-theme-terminal"

baseURL = "http://localhost/"
languageCode = "en-us"
title = "L's Little Blog"
paginate = 10

[params]
 themeColor = "green"
 centerTheme = true
 readingTime = true
 toc = true

