baseURL = 'https://luhuizu.github.io/My-Little-Blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'


[module]
 [[module.imports]]
  path = "github.com/panr/hugo-theme-terminal"

[params]
 themeColor = "green" # orange,blue,red,green,pink
 centerTheme = true
 readingTime = true
 toc = true
 paginate = 10

# Global menu (Option A)
 [menu]
	[[menu.main]]
		name = "Post"
		url = "/post/"
		weight = 1
